# Site settings
title: OhanaMC
tagline: By Bazza
description: > # this means to ignore newlines until "baseurl:"
  Space for site description for Google search results and such.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ohanamc.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass
plugins:
  - jekyll-seo-tag


# Collections
# Add new panels as HTML files inside the _panels folder
collections:
  - panels